version: 2.1

# Define the jobs we want to run for this project
jobs:
  build_dev:
    docker:
      - image: google/cloud-sdk:355.0.0
    steps:
      - checkout
      - run:
          command: |
            echo "--------------------------------------------------------------------------------"
            echo "Using Dockerfile"
            cat ./Dockerfile
            echo "--------------------------------------------------------------------------------"
            gcloud config set project data-fabric-323905
            echo ${GCP_SERVICE_ACCOUNT_ADMIN_CIRCLECI_SVC} | base64 --decode > gcp_project_key.json
            gcloud auth activate-service-account --key-file gcp_project_key.json
            gcloud config list
            echo "--------------------------------------------------------------------------------"
            gcloud run deploy car-svc-test --region=asia-east1 --source .

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build_dev