version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    steps:
      - checkout
      - run: gcloud run deploy car-svc-test --region=asia-east1 --source . --namespace=data-fabric-323905 --service-account=${GCP_SERVICE_ACCOUNT_ADMIN_CIRCLECI_SVC}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
