version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: google/cloud-sdk:335.0.0
        auth:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
    steps:
      - checkout
      - run:
          command: |
            echo "--------------------------------------------------------------------------------"
            ls -al
            echo ${HOME}
            echo "Using Dockerfile"
            cat /Dockerfile
            echo "--------------------------------------------------------------------------------"
            gcloud config set project data-fabric-323905
            echo ${GCP_SERVICE_ACCOUNT_ADMIN_CIRCLECI_SVC} | base64 --decode > gcp_project_key.json
            gcloud auth activate-service-account --key-file gcp_project_key.json
            gcloud config list
            echo "--------------------------------------------------------------------------------"
            export IMAGE="asia-east1-docker.pkg.dev/data-fabric-323905/cloud-run-source-deploy/car-svc-test@sha256:${CIRCLE_SHA1}"
            echo "Creating image -> ${IMAGE}"
            gcloud builds submit --tag ${IMAGE}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
