version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: google/cloud-sdk:335.0.0
        auth:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
    steps:
      - checkout
      - run: gcloud run deploy car-svc-test --region=asia-east1 --source . --namespace=data-fabric-323905 --service-account=${GCP_SERVICE_ACCOUNT_ADMIN_CIRCLECI_SVC}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
