version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: google/cloud-sdk:335.0.0
        auth:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
    steps:
      - checkout
      - run:
        command: |
          echo "--------------------------------------------------------------------------------"
          echo "Using Dockerfile"
          echo
          cat ${HOME}/tmp/Dockerfile
          echo "--------------------------------------------------------------------------------"
          echo

          cd ${HOME}/tmp
          export IMAGE="gcr.io/<< parameters.gcp_project_id_container_repository >>/<< parameters.svc >>:${CIRCLE_SHA1}"
          echo "Creating image -> ${IMAGE}"
          gcloud builds submit --tag ${IMAGE}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
