version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: google/cloud-sdk:335.0.0
        auth:
          username: ${DOCKERHUB_USERNAME}
          password: ${DOCKERHUB_PASSWORD}
    steps:
      - checkout
      - run:
          command: |
            echo "--------------------------------------------------------------------------------"
            echo "Using Dockerfile"
            echo "--------------------------------------------------------------------------------"
            export ${CIRCLE_SHA1}
            echo ${CIRCLE_SHA1}
            echo "--------------------------------------------------------------------------------"
            export IMAGE="asia-east1-docker.pkg.dev/data-fabric-323905/cloud-run-source-deploy/car-svc-test@sha256:${CIRCLE_SHA1}"
            echo "Creating image -> ${IMAGE}"
            gcloud builds submit --tag ${IMAGE}

# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
